name: fridge_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.5
  cupertino_icons: ^1.0.2
  bouncing_widget: ^2.0.0
  fluttertoast: ^8.2.2
  page_transition: ^2.0.9
  pin_code_fields: ^7.4.0
  amplify_flutter: ^1.0.0
  amplify_analytics_pinpoint: ^1.1.1
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
  - family: Lato
    fonts:
      - asset: lib/assets/fonts/Lato/Lato-Regular.ttf
      - asset: lib/assets/fonts/Lato/Lato-Bold.ttf
      - asset: lib/assets/fonts/Lato/Lato-Thin.ttf
        weight: 200

