name: fridge_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amplify_flutter: ^1.0.0-next.0+1
  amplify_authenticator: ^1.0.0-next.0+2
  amplify_auth_cognito: ^1.0.0-next.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
  - family: Lato
    fonts:
      - asset: lib/assets/fonts/Lato/Lato-Regular.ttf
      - asset: lib/assets/fonts/Lato/Lato-Bold.ttf
      - asset: lib/assets/fonts/Lato/Lato-Thin.ttf
        weight: 200

